apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-blocked
  namespace: miniflux
spec:
  redirectRegex:
    regex: "/metrics"
    replacement: "/"
    permanent: true
