---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: git-reconcilers
spec:
  encryptedData:
    password: AgByeAvMEAT6ZG0GrL8yrisBoI1KwcRrjMKkYPNThZ15GOqtvEMXqETHTy2qOv9juZAIcSffE8FX7hmGEiiab6Jufo80hWkPj7NcSZMWPcJidSo2z8g6ki/tSNE3XJmQO6Fg0NcqI/BrIpnDSOYtsMncZTsfbe057tgpEtI7m7v6HxIDP0urwEbEpzvBfHUrPnWyg9/9w8jS2pvGhce3bma55JRzYmThYdHDAOLqprVkXPC63YTMB/TqWUnLWxduL2/nzQrqPHiL8xvXo+gKEK89XbGarBi4fl3+JxD0pvzgSK9YztoXqqU2uNr6VR8Xl8AARP7pMkozIDVD3/HMgTWCUf0PNbzNQ3jCq6doPuGzeBfIB08MJ5krPRu76QBhVWYnshk68c+U1KPiLPQErh25ubQlTrHr1SS5VUHzV+x4ngotAwmzUP1KFWQlswpvhLHyVC6ry9bzdVe098EkdlWUZ3miXYD2+qdBhK9cq/hp/yg7GRsOOGiLu7uS7ZaSL9f9QwWso+sU6pKpc6gUpfrMVttfko2rmz2nRN/4vVMlZMpvjTplWN97z0he8f0ZKeETvwJtB1mnBCYZwQTxZIuu/MNZ21be2Wk58h1DpCE3wjNNWKWEVFq562KkpzdtFcLem0lVwv49DeLWyUpGNJDNi16PVWodkP6Hua23BhyC8ljBxOBHbfVY6CT3kHKWnY6oGfMSptWg7I4gNQTdD6c9BebUSpZ3y5shQ3lGQTRFaxPh32m5jDB6
    username: AgBIu6V3fEWjEkUhWjdPLAgK8PH/GECfDMRjfio/K0D677YJATrmOfblMXM6IFocp7nk45i4HOSm0ntObAgyQyRkPY8U9MNKWLtWzsaOMkEZ1eYhScf0Sq5AiBmgMDke7txJHqqQFs2QCPnWfAcVGVxCwLffcV9lzjaQ8k1TMsuSM2YIVKKoilsfW5rtE/hQgDwClaTUkEjivUp4MZN/cYo7Fyq3lEWRfrPNl2ZhcavdPyUnVx2MIeCu+BJTgXMA+T3x2HfFKcvaBk3lv3Gc9YU3lrsv1hKxHf1vB13B6Yb04oWz8uz5QJ7wac4+S0MjKuGBivnLXFrmm1QtkVurAg5P7P2+vzjSL7vD1JsHieqR+R/mcj977mCsl7Dzic1vPInq1NdlKgYvT1q70dgcU/5kB+Yuc0IFvTv2MR/IgEA9VjMLkXkLvUS/5yFCUF0pt9KHMeEVnudU0UIHQ4+jhU11H2AemNe85Iy4sb2P8p9foSKIe3jdKUZpukoaMMEM0rfZhNEQjy7Kn8/FgYJ2k/yAJ+bkrprMWYdngMHM3COOR4L9lgnd1oxLbK/JKOxeodF5/3ajTLANBHVoH8wYTIDJPO9owR5oK2CsEwaj3PiqfDgXziPjcTVIam4KCnR+2+m/qVZ6Tf037tlb3uehgx49QunukOBx/RO7mZPWMM8RGOpjbk9gh5Dj7dlLPtRNOkpZN4ngZgs=
  template:
    metadata:
      creationTimestamp: null
      name: git-credentials
      namespace: git-reconcilers
