---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: misc-k3s
  namespace: git-reconcilers
spec:
  interval: 5m0s
  url: https://github.com/zrui98/misc-k3s
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: misc-k3s
  namespace: git-reconcilers
spec:
  interval: 5m
  path: "."
  prune: true
  sourceRef:
    kind: GitRepository
    name: misc-k3s