apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: flux-podscrape
  namespace: flux-system  # Change to your desired namespace
spec:
  namespaceSelector:
    matchNames:
      - flux-system  # Change to the namespace where your service is running
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - source-controller
          - kustomize-controller
          - notification-controller
          - image-automation-controller
          - image-reflector-controller
  endpoints:
    - port: http-prom  # The port name from your service
      path: "/metrics"  # Metrics path
      interval: 30s