apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: source-controller
  namespace: flux-system  # Change to your desired namespace
spec:
  namespaceSelector:
    matchNames:
      - flux-system  # Change to the namespace where your service is running
  endpoints:
    - port: http-prom  # The port name from your service
      path: "/metrics"  # Metrics path
      interval: 30s