apiVersion: operator.victoriametrics.com/v1beta1
kind: VLogs
metadata:
  name: vm-logs
  namespace: vm
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: type
            operator: In
            values:
            - storage
  retentionPeriod: "12w"
  removePvcAfterDelete: true
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  resources:
    requests:
      memory: "500Mi"
      cpu: "250m"
    limits:
      memory: "4Gi"
      cpu: "500m"