---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-users
  namespace: authelia
spec:
  encryptedData:
    users_database.yml: AgB+yiHZhQrrRGYb2gPDH5YIycP7I7gj4HYC+WFr1i+PGli9klR/vrDaQQFXNnZ5o8HM0Gf8RDWpxYf9U0LqKPYxF8Ht7OgjB07Za7N4zmbY+q6s2pPEdbrrFWpYZTCAeHhHNwa8D0FGN3YFC+aUBTkXetECus0xNdvRQOM9YM4562uRNXiNRJBW59mo0147jnyEsvxBt6ZBcoWClnFaS45dwXN0nkyQiJaHrga0Pbq6W/QTQJ9i8KwVMsTEUTmt7ckf1mhqlHx5SpM3N19mQ/a8yeCZwwzZJH3TeektY/ZMDHCfbaMea71eGcWaI1MNTGI+sEXsnuqaK1vg5+0wWnlWC6ObkQypQGmLzT08yegXHLPpz+wLW59roOrbgk5nAD4eD2a4ZAEvGCn7cf3bbdVP0vPU/PsvT4Mxt6rdn5/aqdNCWhG6iba7y0TWBiAWl7XFEd87WEQulEupmGMS3wxtynauc2D9R1HFpR4rW0HXwJJa/fhk0Mt4oA2F3AUonggd+ZZiOMcoe4A+7RvVIy1WGLqx+Vc8tRi8GNHsdlVd11PYsERe/+OFBP96LiUNJAKgHw+OP+Wf7ErMyHWouOZcM7LcXucw7ddEJxZu6o56dGaiUHz5ExQBics4sZ1z2z9DySbHwDks8j3tPUIPDLbTJhgJa1GMTaMTllldyKoQ7meTRJCPe3qEBpwUoFlGmQ1lGZjXn5OLLeeZB9VI4wIAJFKwKKrIzcPiGdwS4B4tMhL5T2sd2eNsfybjhD8vH/86+9zVXYRjmzvPbYRB6OZn+Sd1P78fv686HZPZp8uudNM8W9oUaI75PDTaJ4iFUumcCF2MHVkSrVW7ExrIBkG6Ub/e21WDngHTbkMAtId4WxDlB5ua3x0LNSVaDIEmIeup4QgJTx62g8C74uJiO0Kh/Ru/KJVBrexRtjoY62sUr7zewbOmO/tQgzZUA4Avw420GklQi7mMGdvE4YjSnHXXb9lEeNz1TdOnLH7UppyASyEZmfqmLOKMaM6ZD3LFzJX7UmcJ4iQ=
  template:
    metadata:
      name: authelia-users
      namespace: authelia
