---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-users
  namespace: authelia
spec:
  encryptedData:
    users_database.yml: AgBLPyJgG9AcIXX/YGGw0hiR0hU5k7O0a681DKIUThUuXx2c/8LvR16flgU2IJn126YQhHbmi4Pi2a0MrH8jy9/VOkwc85NvMnUD9VXPM0fSnd2kj9rDl8OzgR6Ynwo8HUyfStKv+Xc1aCPNy/lWdQPYts42LZ5x3J6NBWLbIDEQZcwuF6QKkMUlxKFcuLfmD7/FMRsxbtGR3BCRmND21Exka8X99ROL0DWlHFkw0KjWS2DPwAAlOp1USg7Zm1I/w2wgaXsI5/9oWF6/HaAFkO4m0mK5uLioS1f63FWKUiPApQ/SjkmbvvO2lrF+nN8Ul5BEH6m3TRm9XW+Of6jUayg4078HbJyjwwvc0tITkO7qblcpWa0ETcFH3O/VhEAVNzRvkxzwByFtAGRSQ2hi4dKUUvszuvaatmDHoiP7BXyg8PPHPXa1MMfXHKM6YKV4x0qgagRFWi4MXGULk5IFeDPu4O7SCWFVEggvND3al3KMtijXsBP7zzcLLDI6BkeJSNrGHrPLdAHqpJhneZeEcVdtHyZTetaUqAiRm403iSm8BwxdSscQq4E8vyhefH5NjwW/vTXbjeC/WSmkOWCRTcB2QgZaW6dU+JsQgq2eF/YZA0gctyayTlqzqOMGErl0fNxoLwxe9lHmJK3BH67u/A4vyeP+3c9lWYQPqN4P3e8aNIvLcc4rRFnDi4J+Y78dI9Phobm60oGO5GwdMzQN0+Qu62ujU+SyLLKl2CUED8cYfGBXQtiCLBe18Ur2gYVDatUInX2mMEHemo+yXAx0NSH1aDLSyqXsy39Cf9dNt01IUCR+9dHNEoDJme/DbMlcN+Ikjhw4J1N461aOup5AQ/iRtYhU4emon+nZ2zkhJyiAeUj/DDY1b+FGzvEpUVRPyqN7HXR26CvY+M72AnLBF4shhNZJ+iTm8gdNFhTtd91Th3Ybu4vReFtWOO89qSmopddVCmwoAf8lflJ2ECx8Bnb0HXBktN3n7WS1icaN/ePKGrxoqPPFoD3+xxWOmsq/Kx5GaNgNLJvs
  template:
    metadata:
      name: authelia-users
      namespace: authelia
