---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 1h
  url: https://dl.gitea.com/charts/