apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo
    namespace: flux-system
  interval: 24h0m0s
  timeout: 10m
  releaseName: forgejo
  targetNamespace: forgejo
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 30m
  driftDetection:
    mode: enabled
  values:
    strategy:
      type: Recreate
      rollingUpdate: {}
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: type
              operator: In
              values:
              - storage
    gitea:
      admin:
        existingSecret: forgejo-admin-secret
      config:
        APP_NAME: "Forgejo"
        service:
          DISABLE_REGISTRATION: true
        indexer:
          REPO_INDEXER_ENABLED: true
        actions:
          ENABLED: false
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - hosts:
          - git.zrui.dev
          secretName: forgejo-tls-secret
      hosts:
        - host: git.zrui.dev
          paths:
            - path: /
              pathType: Prefix
              port: http
    persistence:
      enabled: true
      create: true
      mount: true
      claimName: forgejo-shared-storage
      size: 15Gi
      accessModes:
        - ReadWriteOnce