apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: forgejo
  namespace: flux-system
spec:
  interval: 10m
  url: oci://code.forgejo.org/forgejo-helm/forgejo
  ref:
    semver: ">=16.0.0 <17.0.0"