apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- service-account.yaml
- crs-configmap.yaml
- deployment.yaml
- service.yaml
- vmscrapeconfig.yaml
