apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  staticTargets:
    - targets:
        - kube-state-metrics.kube-system.svc.cluster.local:8080
  jobName: kube-state-metrics