apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: woodpeckerci
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: oci://ghcr.io/woodpecker-ci/helm/woodpecker
  ref:
    tag: 3.4.2