apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodpecker
  namespace: woodpecker
spec:
  chartRef:
    kind: OCIRepository
    name: woodpecker
    namespace: flux-system
  interval: 24h0m0s
  timeout: 10m
  releaseName: woodpecker
  targetNamespace: woodpecker
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    agent:
      env:
        WOODPECKER_BACKEND: "kubernetes"
        WOODPECKER_BACKEND_NAMESPACE: "woodpecker"
        WOODPECKER_BACKEND_K8S_VOLUME_SIZE: "6Gi"
        WOODPECKER_MAX_WORKFLOWS: 5
      serviceAccount:
        name: "woodpecker-agent"
    server:
      createAgentSecret: true
      env:
        WOODPECKER_HOST: https://ci.zrui.dev
        WOODPECKER_OPEN: "false"
        WOODPECKER_FORGEJO: "true"
        WOODPECKER_DISABLE_USER_AGENT_REGISTRATION: "true"
        WOODPECKER_FORGEJO_URL: https://git.zrui.dev
      extraSecretNamesForEnvFrom:
        - woodpecker-server-secret
      ingress:
        enabled: false
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        tls:
          - hosts:
            - ci.zrui.dev
            secretName: woodpecker-tls-secret
        hosts:
          - host: ci.zrui.dev
            paths:
              - backend:
                  serviceName: "ci.zrui.dev"
                  servicePort: 80
                path: "/"