apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: vector
spec: {}
status: {}
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: Agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.44.0-distroless-libc
  name: vector
  namespace: vector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: Agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.44.0-distroless-libc
  name: vector
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: Agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.44.0-distroless-libc
  name: vector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector
subjects:
- kind: ServiceAccount
  name: vector
  namespace: vector
---
apiVersion: v1
data:
  agent.yaml: |
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      kubernetes_logs:
        type: kubernetes_logs
    transforms:
      kubernetes_container_logs:
        type: remap
        inputs:
          - kubernetes_logs
        source: |
          .message = .message
          .container = .kubernetes.container_name
          .pod = .kubernetes.pod_name
          .namespace = .kubernetes.pod_namespace
          .node = .kubernetes.pod_node_name
    sinks:
      victorialogs_sink:
        inputs:
          - kubernetes_container_logs
        type: elasticsearch
        endpoints:
          - "http://vlogs-vm-logs.vm.svc:9428/insert/elasticsearch/"
        encoding:
          except_fields:
            - "kubernetes"
        mode: bulk
        api_version: "v8"
        healthcheck:
          enabled: false
        query:
          _msg_field: "message"
          _time_field: "timestamp"
          _stream_fields: container
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: Agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.44.0-distroless-libc
  name: vector
  namespace: vector
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: Agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.44.0-distroless-libc
  name: vector
  namespace: vector
spec:
  minReadySeconds: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: Agent
      app.kubernetes.io/instance: vector
      app.kubernetes.io/name: vector
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: Agent
        app.kubernetes.io/instance: vector
        app.kubernetes.io/name: vector
        vector.dev/exclude: "true"
    spec:
      containers:
      - args:
        - --config-dir
        - /etc/vector/
        env:
        - name: VECTOR_LOG
          value: info
        - name: VECTOR_SELF_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: VECTOR_SELF_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VECTOR_SELF_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROCFS_ROOT
          value: /host/proc
        - name: SYSFS_ROOT
          value: /host/sys
        image: timberio/vector:0.44.0-distroless-libc
        imagePullPolicy: IfNotPresent
        name: vector
        ports:
        - containerPort: 9090
          name: prom-exporter
          protocol: TCP
        volumeMounts:
        - mountPath: /vector-data-dir
          name: data
        - mountPath: /etc/vector/
          name: config
          readOnly: true
        - mountPath: /var/log/
          name: var-log
          readOnly: true
        - mountPath: /var/lib
          name: var-lib
          readOnly: true
        - mountPath: /host/proc
          name: procfs
          readOnly: true
        - mountPath: /host/sys
          name: sysfs
          readOnly: true
      dnsPolicy: ClusterFirst
      serviceAccountName: vector
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config
        projected:
          sources:
          - configMap:
              name: vector
      - hostPath:
          path: /var/lib/vector
        name: data
      - hostPath:
          path: /var/log/
        name: var-log
      - hostPath:
          path: /var/lib/
        name: var-lib
      - hostPath:
          path: /proc
        name: procfs
      - hostPath:
          path: /sys
        name: sysfs
