---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: curseforge-secrets
  namespace: minecraft
spec:
  encryptedData:
    cf-api-key: AgAVh3ktEzKpFkx/CpGjZqEuMYitvyWN6Me6FmSAvQTc7UvgoPvJKcdTEuk794kyyFYaSTNIyJLWWmCGo0gJmQ8qmzkCgBuDa0p7vTUnCqtfXOz4/0aaFVyCrIzTmRMZmA5pqelPIABflsIgNQr19Ck4gLYUoue5QRlnOVJXrc+oCPzyVMrnoafnz6dFy5B47nZau3p6GEMHqtAO2VqLXE52GDMg1WoySU8a+GmaYXhq6dL4JvuFvHrvB6wsQR/ZavWFdCBNlDtU1L4IYgaqLK/vMKy387cXHC7NWYVXaVlLtKUB8qoXbpcIemxaXAoSgx1AJqOPmBskQkSF5nrD7qPuaJ/MRbTcKjOyNH1PZQCA+EQ3iZncR9k6EzmEc7WRz72aE+viqAGUh2bTGSfDRN/2CSQJ6yHOj4o8zTPtgnYcysj2XPqCK6GQr9tZytpAIX0rb6qeSdvHS8hw5o3MVYSzCcif2QfmYOu/aEkPUpY2hdBcr9E1Y2KNQ8/jVgS2x+g+4JBZ7/GpecEBTuhK0CUay8hvrESod/+VZvOEHVCi3vobAFt5YjfRdKvW8jDFgISk/hpejgfUMKgkW+z9OfjKLSpNUHqXHrE4YyXbxQStHByZQK8AD8OPQdCLmGkt2bBg4PdYqB2GS/w8gr2QzK3xFujbp/zXI0lEvb2vRZzoRSCqyVrmaoUm8Lev1AidT0a14GKKmS30RMApARZp4/6ssaX++Jgcm6dRmEpgrHwonxIRWG4cFbfcFebVJ2z4cKiM8xg/udVeZfa8psQ=
  template:
    metadata:
      name: curseforge-secrets
      namespace: minecraft
