apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-datadir
  namespace: minecraft
  labels:
    app: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backupdir
  namespace: minecraft
  labels:
    app: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: minecraft
  name: minecraft-server
  labels:
    app: minecraft
spec:
  serviceName: minecraft-server
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: type
                operator: In
                values:
                - storage
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        imagePullPolicy: IfNotPresent
        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP
        env:
        - name: EULA
          value: "true"
        - name: MOD_PLATFORM
          value: "AUTO_CURSEFORGE"
        - name: CF_SLUG
          value: "monifactory"
        - name: MEMORY
          value: "6G"
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: curseforge-secrets
              key: cf-api-key
        resources:
          requests:
            memory: "7Gi"
            cpu: "2"
          limits:
            memory: "7Gi"
        volumeMounts:
        - mountPath: /data
          name: minecraft-datadir
        - mountPath: /backups
          name: minecraft-backupdir
      volumes:
      - name: minecraft-datadir
        persistentVolumeClaim:
          claimName: minecraft-datadir
      - name: minecraft-backupdir
        persistentVolumeClaim:
          claimName: minecraft-backupdir
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565
    protocol: TCP
