apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-datadir
  namespace: minecraft
  labels:
    app: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backupdir
  namespace: minecraft
  labels:
    app: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: minecraft
  name: minecraft-server
  labels:
    app: minecraft
spec:
  serviceName: minecraft-server
  replicas: 0
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - compute
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        imagePullPolicy: IfNotPresent
        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP
        env:
        - name: EULA
          value: "true"
        - name: ENABLE_WHITELIST
          value: "true"
        - name: ENFORCE_WHITELIST
          value: "true"
        - name: MOD_PLATFORM
          value: "AUTO_CURSEFORGE"
        - name: CF_SLUG
          value: "monifactory"
        - name: MEMORY
          value: "5G"
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: curseforge-secrets
              key: cf-api-key
        resources:
          requests:
            memory: "6Gi"
            cpu: "1"
          limits:
            memory: "6Gi"
        volumeMounts:
        - mountPath: /data
          name: minecraft-datadir
        - mountPath: /backups
          name: minecraft-backupdir
      volumes:
      - name: minecraft-datadir
        persistentVolumeClaim:
          claimName: minecraft-datadir
      - name: minecraft-backupdir
        persistentVolumeClaim:
          claimName: minecraft-backupdir
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft
  annotations:
    mc-router.itzg.me/externalServerName: "mc.k8s.zrui.dev"
spec:
  type: ClusterIP
  selector:
    app: minecraft
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565
    protocol: TCP
