apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: vm-operator
  name: vm-operator
  namespace: vm
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
          - name: VM_ENABLEDPROMETHEUSCONVERTER_SERVICESCRAPE
            value: "false"
          - name: VM_ENABLEDPROMETHEUSCONVERTER_PROMETHEUSRULE
            value: "false"
          - name: VM_ENABLEDPROMETHEUSCONVERTER_PROBE
            value: "false"
          - name: VM_ENABLEDPROMETHEUSCONVERTER_SCRAPECONFIG
            value: "false"