---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgCUA/sM98f8MWUMXtdJNtHaHYh7tdPO5eGm8XbwZ8OdtazJpyVVZgWO2GT09VbDERtWUXFjVOAGqsQQvd/qzSJ12PJbmOXOtNd96fJpvP7zM1XXIX0dIOoovplBeFzBAWfgbuoaWjxJfa/726OjF9gcxse4OFceLPJzsEnJjU+P90cTG8xnnv45NhwToJkRQKw+Cu4eO8W1NBcRTioojS5UfKfd6dB1TWBofwr2BRHN2Fgo80ab+iRuzRFtINE6RbsuA+pZ51+LZoKh1TrW+STMkhnFQBMaVI5aQE+NhwDowt+WnWaF3TO3dHJvfw2raCg/0yVA7rcy9gqxPCqva/OAWyq2EPzgKlG95jiKO0cS18ksqP1sogrlJ7a6LR164+5YjgepcNEpXN7LM53mTymfSakKJEdFp+7MGsr7xeXUdLHsUY9RF0SvXwfW/dpnwRIzFJuKIcp5/HTO+Vr+bCKbxe+80m6gqTVRhiPMgQRw1CbI/WQq4bndRLl8QbviVmsIzAeD55qUjpBOjmvEwJ9sMn11GNmkFDTSoPPSVJNsF+3vF1dEZiNJSEZ829OxpgmeYi7C+CGQyyVIhVWeoS+Nxxoa7XrmU6gTa8Rukq6Jg+bnlGkJbpjKIFk4EOTaOloF4JP2kSMkvS17gbJbGBRBSFheNN1o86ZWpnF6EiEeugF8m8/cJZUgoiIBOJaWozP8veVNVFcfdNJQ
  template:
    metadata:
      name: postgres-secret
      namespace: postgres
