---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    password: AgAXQ0MV7BIZP0IVPmAQZNnzbnF6xlfoAWbpKeU8UQz5trbAbEYVOPq74nAl7cjVLHgG/SsYForlf78Ay5/+YNGbHdcv5xy3g0MgPpAH7LNvDC7rCpznDtK6fmwxCxkQPqjC4/kjZ9oCHeIGINrQ+ZY9I5ZxLjQEozx//o0St8dsSaNQHTdhfOIWc4t0tjSI/g3TYXUbHiN/y+88aPpMf2WI0CItD7JvoDRbrfk3P9uehpgSpa1bmmjRJRwtc9AvUBt2pWH/6rYjy48CWwzJbdkG8lFwb7I6hm1oVwtg+EcwuuY9v1J5yBAJEz7mVHjtHC+15d9BdnB/enAhAFr9S9rzSXr5HGhaKfSIA+dXXpBjC3I0xuVA2YkAGo7TjshIcZGFvXZxCfvlRJlvouT8iOV7T82lFKvwixGFCbB8Vxadrup/7g2focCDim1TTClCoT57kH0tvwhOIOGVBAcG85jag9X/esvrR5rl9dHgEC165LjRsravq7q3THwEs30c3bejuh1bxNQzsDhhwNFtwnY2BiL7jd78Qd/q6/ZEVZ6q+XcmgGC/RIA/Brg674qX8uC4cVwqz/+j4F2c6HdF8yV08/sKBPBtTqYMgz/6cTftabyoGjciODK+nqm3ggspEgQfR2Sm1Y5nArcqD3ywl6AzAKqXiXHqlJPZ5A5MQVthlx0vHTixHfuMMpfVzWhrzCOC/5WITWQtt/J6i5UOzWM=
  template:
    metadata:
      name: redis-secret
      namespace: redis
